[plugin]
id = "wso2.apim.catalog-compiler-plugin"
class = "io.ballerina.wso2.apim.catalog.ServiceCatalogCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/wso2.apim.catalog-compiler-plugin-0.1.0-SNAPSHOT.jar"

[[dependency]]
path = "lib/ballerina-to-openapi-2.0.3.jar"

[platform.java17]
graalvmCompatible = true
